version: "3"

services:
  db:
    image: postgres:14
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: hw
      POSTGRES_PASSWORD: hw
      POSTGRES_DB: hw
    volumes:
      - ./pg_data:/var/lib/postgresql/data